// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8N7L5c4lJgSYk1aHT4AIVGxAy_WqwgdU',
    appId: '1:1085391112158:web:163f92a95f7328640bff4f',
    messagingSenderId: '1085391112158',
    projectId: 'chats-af816',
    authDomain: 'chats-af816.firebaseapp.com',
    storageBucket: 'chats-af816.appspot.com',
    measurementId: 'G-4GS031S3CR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBX8d-P2tQRCB8rz1-KMjvLnKjiLeBBe9o',
    appId: '1:1085391112158:android:b58bbcae39de230c0bff4f',
    messagingSenderId: '1085391112158',
    projectId: 'chats-af816',
    storageBucket: 'chats-af816.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvqKxRZPcNnS1Ww3BRIxZLnzxR3LUJulE',
    appId: '1:1085391112158:ios:a952052c670046370bff4f',
    messagingSenderId: '1085391112158',
    projectId: 'chats-af816',
    storageBucket: 'chats-af816.appspot.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvqKxRZPcNnS1Ww3BRIxZLnzxR3LUJulE',
    appId: '1:1085391112158:ios:a952052c670046370bff4f',
    messagingSenderId: '1085391112158',
    projectId: 'chats-af816',
    storageBucket: 'chats-af816.appspot.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8N7L5c4lJgSYk1aHT4AIVGxAy_WqwgdU',
    appId: '1:1085391112158:web:813e2b6881c8ad0f0bff4f',
    messagingSenderId: '1085391112158',
    projectId: 'chats-af816',
    authDomain: 'chats-af816.firebaseapp.com',
    storageBucket: 'chats-af816.appspot.com',
    measurementId: 'G-T0NE85E3WD',
  );
}
